name: Ejecutar Prediccion Llobregat
on:
  schedule:
    - cron: '*/30 * * * *' # Esto significa: cada 30 minutos
  workflow_dispatch:      # Permite ejecutarlo manualmente si quieres probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias
        run: |
          Rscript -e 'install.packages("pacman")'
          Rscript -e 'pacman::p_load(httr, jsonlite, dplyr, purrr, tidyr)'

      - name: Ejecutar Script
        run: Rscript script-opendata.R

      - name: Guardar cambios en GitHub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*.csv
          git commit -m "Auto-update: $(date)" || echo "No hay cambios"
          git push
