name: Prediccion Llobregat 30min
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias de Linux
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar paquetes R
        run: |
          Rscript -e 'install.packages(c("pacman", "httr", "jsonlite", "dplyr", "purrr", "tidyr"), repos="https://cloud.r-project.org")'

      - name: Ejecutar Script
        run: Rscript script-opendata.R

      - name: Commit y Push de los datos
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*.csv
          git commit -m "Datos actualizados $(date)" || echo "Sin cambios"
          git push
